# Generated by Django 6.0.7 on 2026-07-08 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBaseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('question_en', models.TextField()),
                ('answer_en', models.TextField()),
                ('question_ur', models.TextField(blank=True, null=True)),
                ('answer_ur', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Knowledge Base Entries',
            },
        ),
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('title', models.CharField(default='New Chat Session', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConversationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('response_text', models.TextField()),
                ('language_detected', models.CharField(choices=[('EN', 'English'), ('UR', 'Urdu')], default='EN', max_length=2)),
                ('register_detected', models.CharField(choices=[('PLAIN', 'Plain Language'), ('LEGAL', 'Legal Terminology')], default='PLAIN', max_length=10)),
                ('find_lawyer_shown', models.BooleanField(default=False)),
                ('find_lawyer_clicked', models.BooleanField(default=False)),
                ('is_flagged', models.BooleanField(db_index=True, default=False)),
                ('flagged_note', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='lex_ai.conversationsession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LexAISystemPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_prompts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lex AI System Prompt',
                'ordering': ['-updated_at'],
            },
        ),
    ]
