# Generated by Django 6.0.7 on 2026-07-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lex_ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LexChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=255)),
                ('user_message', models.TextField()),
                ('ai_response', models.TextField()),
                ('language', models.CharField(default='EN', max_length=10)),
                ('register', models.CharField(default='PLAIN', max_length=10)),
                ('show_lawyer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lex Chat History',
                'verbose_name_plural': 'Lex Chat Histories',
                'ordering': ['created_at'],
            },
        ),
    ]
